### ISSUE TITLE
Critical.hpp Linux build

### ISSUE THREAD

**Issue by smr277** [michaelbecker/freertos-addons#1]
Hello,
First off, thank you so so much for all the work you've put in - this library is AMAZING. Saved me so much time, and it's so simple to use. 
However...I can't seem to get Critical.hpp to work. First, there seems to be a semicolon on line 120 that shouldn't be there...just a guess, but I could be wrong. Once I delete that, I still can't get it to build, with errors such as:
portmacro.h:133:71: error: too few arguments to function ‘void vPortClearInterruptMask(long int)’
 #define portCLEAR_INTERRUPT_MASK_FROM_ISR(x) vPortClearInterruptMask(x)

Any ideas on what's going on or what I should look into to fix it?

**Comment by smr277** [comment]
Thanks for taking a look at this Michael! Any way I can help?

**Comment by michaelbecker** [comment]
Thanks for the offer. I already found the issue and am finishing up the fix. It should be posted sometime tonight. If you need to keep working, you can comment out EnterFromISR() / ExitFromISR() along with removing that semicolon and should be able to keep going until I can push version 1.3.2.

**Comment by smr277** [comment]
You're amazing, thanks so much!

**Comment by michaelbecker** [comment]
Should be resolved with release 1.3.2.
