### ISSUE TITLE
Can freertos-addons works on NXP frdmk64f?

### ISSUE THREAD

**Issue by minjiexm** [michaelbecker/freertos-addons#17]
hi. Dear expert:

I tried to run the demo freertos-addons/Linux/Demo/Linux_g++_dynamic_tasks on NXP frdmk64f.
But I found when the dynamic CPP task start in another CPP task, it will report HardFault_Handler error.

Can I run the linux example on frdmk64f? 

Thanks.

**Comment by michaelbecker** [comment]
Hi.

The short answer is I don't know. 

The long answer is that the wrapper library uses standard C++. If your compiler supports standard C++, then everything should work with respect to the wrappers. If it's not working, you are going to have to troubleshoot the compilation and linking. 

If you are trying to _directly_ use the that demo, please note that it's targeted for a full Linux distribution running the Linux simulator as a way to demonstrate the use of the wrappers. For this example to work without changes, you should be compiling it under Linux and running it under Linux. When I look up "NXP frdmk64f" it looks like a mid-size microcontroller. Does Linux run on this board?

Best regards,
-Mike
