### ISSUE TITLE
Valgrind sometimes hangs on waiting on xSentinel 

### ISSUE THREAD

**Issue by KKoovalsky** [michaelbecker/freertos-addons#21]
Hi! It's me again with problems with `valgrind`.

When I run an application under `valgrind` the application hands on the first `xTaskCreate`. I debugged the port code and noticed that the code stalls here:

```
portSTACK_TYPE *pxPortInitialiseStack( portSTACK_TYPE *pxTopOfStack, pdTASK_CODE pxCode, void *pvParameters )
{
    ...
        pthread_mutex_unlock( &xSingleThreadMutex );

        while ( xSentinel == 0 );
    ...
}
```
`xSentinel` is set inside `SIG_SUSPEND` signal handler.

Does `valgrind` spoil somehow the use of signals?

**Comment by michaelbecker** [comment]
I've never had valgrind hang for me. It takes _forever_ to start up and execution is much slower, but no hangs. Could you post an example that demonstrates the problem?

**Comment by abeck70** [comment]
Hi Guys, I am stuck also on valgrind's serializing of pthreads preventing this linux port from working. Any tips?

**Comment by abeck70** [comment]
Ok actually based on Mike's comments it takes forever, if you wait long enough (minutes hours??), it works well.
