### ISSUE TITLE
Example using binary semaphore with ISR

### ISSUE THREAD

**Issue by ripe909** [michaelbecker/freertos-addons#27]
I didn't see an examples of using GiveFromISR() for a binary Semaphore within an interrupt...  I would love to see how to handle the parameter pxHigherPriorityTaskWoken (for ARM) and how to handle the Semaphore object in a "C" ISR.

**Comment by michaelbecker** [comment]
The examples I put together are all running under a Linux simulator, making it easier to unit test them all. However, there are no real interrupts on that simulator so consequently there are no examples showing usage of the interrupts. That being said, the pxHigherPriorityTaskWoken argument is a simple pass through. I'm not doing anything with it except passing it to the underlying FreeRTOS call. FreeRTOS itself has a very detailed example of how to use this parameter, at 
https://github.com/aws/amazon-freertos/blob/master/lib/include/semphr.h#L538

If you are using a Binary semaphore object, you should be able to just substitute the C FreeRTOS call from the example with the method call from the object.
