### ISSUE TITLE
Member variable access within Thread class Run() fails when called from scheduler

### ISSUE THREAD

**Issue by thomas-emig** [michaelbecker/freertos-addons#28]
Thanks for the great work!
I'd like to use the C++ Wrappers to start a new project on nRF52840 together with freertos 10. For a first test i wrote an example similar to Linux_g++_simple_tasks:

```
class led_toggle_task : public Thread {
    public:
        led_toggle_task(uint32_t led = 0) :
            Thread(1024, 0),
            led_number(led)
        {
            Start();
        };

    protected:
        void Run()
        {
            while (true) {
                Delay(70);
                bsp_board_led_invert(led_number);
            }
        };

    private:
        uint32_t led_number;
};

int main(void)
{
    ret_code_t err_code;

    /* Initialize clock driver for better time accuracy in FREERTOS */
    err_code = nrf_drv_clock_init();
    APP_ERROR_CHECK(err_code);

    /* Configure LED-pins as outputs */
    bsp_board_init(BSP_INIT_LEDS);

    /* Create task for LED0 blinking */
    led_toggle_task task1(1);

    /* Start the FreeRTOS scheduler */
    Thread::StartScheduler();

    while (true)
    {
        // this should never be reached
    }
}
```

The project compiles. However, the evaluation of the member `led_number` inside `Run()` does not yield the expected result (should evaluate to `1`). I can write and read the value but initially it does not have the value which is stored into the variable by the constructor.

Declaring the variable as static and and initializing it in the global context yields the correctly initialized variable.

Also, declaring `Run()` in the public section and calling `task.Run();` instead of `Thread::StartScheduler();` results in a correctly initialized member `led_number`. The same holds for moving `TaskFunctionAdapter()` into the public section and invoking `Thread::TaskFunctionAdapter((void*) &task1);` instead of `Thread::StartScheduler();`.

My assumption is that when called by freertos, the binding between the variable led_number and its correct memory address somehow gets lost. But I'm not really sure what happens here...

It would be great if you could give me some hints on what is going wrong here.

The code is compiled using `arm-none-eabi-c++` with `-O3 -g3 -DCPP_FREERTOS_NO_CPP_STRINGS -DCPP_FREERTOS_NO_EXCEPTIONS -mcpu=cortex-m4 -mthumb -mabi=aapcs -Wall -Werror -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-builtin -fshort-enums`.

**Comment by michaelbecker** [comment]
Hi Thomas,

The C++ code looks correct. The one thing that stands out to me is you are allocating space for task1 on the stack of the main() function. Because you declare task1 as a local, the whole class is on the whatever the stack is at that point. This _probably_ isn't what you intended to do? What happens if you change your code to:
`
    /* Create task for LED0 blinking */
    led_toggle_task *task1;
    task1 = new led_toggle_task(1);
`
Does that work? What _might _ be happening is that the initial startup stack for this FreeRTOS port is reused when FreeRTOS starts up (the call to Thread::StartScheduler()). 

When I have a minute I'll try digging into this a little bit more.

**Comment by thomas-emig** [comment]
Hi Michael,

thanks for the fast answer. What you pointed out is exactly what is going wrong in my example. I looked into the port.c and it does reset the stack in `vPortStartFirstTask`:
```
#if defined(__SES_ARM)
                    " ldr r0, =_vectors \n"     /* Locate the stack using _vectors table. */
#else
                    " ldr r0, =__isr_vector \n" /* Locate the stack using __isr_vector table. */
#endif
                    " ldr r0, [r0]          \n"
                    " msr msp, r0           \n" /* Set the msp back to the start of the stack. */
```
In this case my task1 will be overwritten by whatever the Scheduler does.

I was a little bit confused because in your examples, it is also allocated using the initial user stack.
```
int main (void)
{
    cout << "Testing FreeRTOS C++ wrappers" << endl;
    cout << "Simple Tasks" << endl;

    cout << "configMAX_TASK_NAME_LEN = " << configMAX_TASK_NAME_LEN << endl;
    cout << "  C++ Thread names can be greater than " 
         << configMAX_TASK_NAME_LEN - 1 << " characters long." << endl;

    TestThread thread1("Thr_Name_1", 1, 1);
    TestThread thread2("Thr_Name_22", 2, 2);
    TestThread thread3("Thr_Name_333", 3, 3);
    TestThread thread4("Thr_Name_4444", 4, 4);
    TestThread thread5("Thr_Name_55555_55555_55555", 5, 5);

    Thread::StartScheduler();

    //
    //  We shouldn't ever get here unless someone calls 
    //  Thread::EndScheduler()
    //

    cout << "Scheduler ended!" << endl;

    return 0;
}
```
But then again, looking into the port.c for the Linux examples shows that it does not overwrite the user stack. So this is a port specific behaviour.

Thanks again for your help solving this problem!
