### ISSUE TITLE
win32 MSVC port

### ISSUE THREAD

**Issue by tolgayilmaz86** [michaelbecker/freertos-addons#29]
I am trying to apply your c++ code to windows msvc demo of freertos without no luck. Do I supposed to rewrite sections like creating thread, semaphores etc. ?

**Comment by michaelbecker** [comment]
You shouldn't need to rewrite anything. What exactly are the errors you are seeing? Did you set your include paths correctly?

**Comment by tolgayilmaz86** [comment]
Hi, I get errors below. I added sources and created a seperate lib file but also using directly the sources files didn't help
1>main.obj : error LNK2019: unresolved external symbol "public: __thiscall cpp_freertos::Thread::Thread(char const *,unsigned short,unsigned long)" (??0Thread@cpp_freertos@@QAE@PBDGK@Z) referenced in function "public: __thiscall TestThread::TestThread(char *,int,int)" (??0TestThread@@QAE@PADHH@Z)
1>main.obj : error LNK2019: unresolved external symbol "public: bool __thiscall cpp_freertos::Thread::Start(void)" (?Start@Thread@cpp_freertos@@QAE_NXZ) referenced in function "public: __thiscall TestThread::TestThread(char *,int,int)" (??0TestThread@@QAE@PADHH@Z)
1>main.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall cpp_freertos::Thread::~Thread(void)" (??1Thread@cpp_freertos@@UAE@XZ) referenced in function __unwindfunclet$??0TestThread@@QAE@PADHH@Z$0
1>main.obj : error LNK2001: unresolved external symbol "protected: virtual void __thiscall cpp_freertos::Thread::Cleanup(void)" (?Cleanup@Thread@cpp_freertos@@MAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "private: static bool volatile cpp_freertos::Thread::SchedulerActive" (?SchedulerActive@Thread@cpp_freertos@@0_NC)

**Comment by tolgayilmaz86** [comment]
ok nevermind I've solved problem.
