### ISSUE TITLE
Probably Invalid MainThreadID

### ISSUE THREAD

**Issue by innerand** [michaelbecker/freertos-addons#32]
Called at this point, this returns the ID of `hSigSetupThread` which is different from the MainThreadID.  

https://github.com/michaelbecker/freertos-addons/blob/8f408a2f37e0322439d9a058b0f8c96bb0db65ab/Linux/portable/GCC/Linux/port.c#L417

Breaks `vTaskSchedulerEnd()` as the actual main thread is never  woken.

**Comment by michaelbecker** [comment]
Closing because we have switched to the new supported POSIX port in the FreeRTOS directory.
