### ISSUE TITLE
Memory corruption of locally created Thread objects.

### ISSUE THREAD

**Issue by Mikey456** [michaelbecker/freertos-addons#34]
Hi,

I am trying to create two Thread objects running their own code in parallel. I am using one of the examples with simple threads for g++. Whenever Thread objects do get created as a global ones, then they do run with no issues. The problem is whenever they do get created on the main stack. During context switch their content does seem to get corrupted and filled up with "random" values. I wonder what might be causing this kind of problem? Creating threads globally is not the best option as tasks do get initialized before the main() function gets triggered, way before any MCU hardware initialization in my code and I would like to have them created later on after the system becomes ready for multitasking.

I am using: 
STM32F429 MCU
FreeRTOS 10.2.1
arm-none-eabi-g++ 7.2.1

Example code that shows the problem:

```
class TestThread : public Thread {

    public:

        TestThread(const char* name, int i, int delayInSeconds)
           : Thread(name, 100, 1),
             id (i),
             DelayInSeconds(delayInSeconds)
        {
            //
            //  Now that construction is completed, we
            //  can safely start the thread.
            //
            Start();
        };

    protected:

        virtual void Run() {

            while (true) {

                TickType_t ticks = Ticks::SecondsToTicks(DelayInSeconds);

                if (ticks)
                    Delay(ticks);

            }
        };

    private:
        int id;
        int DelayInSeconds;
};


/* Declaring them as global objects works */
TestThread thread1("Thr_Name_1", 1, 1);
TestThread thread2("Thr_Name_22", 2, 2);


int main (void)
{
	/* Declaring them as local objects triggers Hard Fault due to memory corruption */
	//TestThread thread1("Thr_Name_1", 1, 1);
	//TestThread thread2("Thr_Name_22", 2, 2);

    Thread::StartScheduler();

    return 0;
}
```

**Comment by michaelbecker** [comment]
Hi Mikey456,

What happens to the stack that main() is using when you start the FreeRTOS Scheduler? This is not the first time someone has reported issues with local vs. global declaration, and so far it's always been because the port specific code in FreeRTOS reclaims the RAM space that main() was using as its stack.

I might suggest a dynamic approach here:

/* Declaring pointers to Threads as globals */
TestThread *thread1;
TestThread *thread2;

int main (void)
{
	/* Create them in main, so you have control of when they are created. */
	thread1 = new TestThread("Thr_Name_1", 1, 1);
	thread2 = new TestThread("Thr_Name_22", 2, 2);

    Thread::StartScheduler();

    return 0;
}

Yes, it's using dynamic memory. But it's doing it only once at system startup, so you don't have to worry about fragmentation.

Hope this helps.

Best regards,
-Mike

**Comment by Mikey456** [comment]
Hi michaelbecker,

I think you right about main stack being reclaimed by FreeRTOS after scheduler starts running. The thread below from FreeRTOS forum explains what is actually happening. I am really surprised that I have never noticed such a behavior in my previous C projects. I think your solution with dynamic allocation of objects might be the only one to mitigate the problem of class constructors being executed before full initialization of the system. Thanks for the suggestion.

https://www.freertos.org/FreeRTOS_Support_Forum_Archive/January_2015/freertos_Main_stack_pointer_reset_when_starting_the_scheduler_e5a776c1j.html

Kind regards.

**Comment by pat1** [comment]
I have lost some days with tests and debug with stm32 before read this issue.
The only examples available written for Linux (and working with Linux) do not have and do not require heap allocation.
I think that some words about this in documentation can help a lot new users
