### ISSUE TITLE
C++ wrappers for FreeRTOS status

### ISSUE THREAD

**Issue by aminya** [michaelbecker/freertos-addons#36]
What's the status of FreeRTOS C++ wrappers? Has it completely implemented FreeRTOS?
I see the project is not updated for a while and there are pull requests that have remained open.

**Comment by michaelbecker** [comment]
The project is basically in maintenance mode right now. All core functionality that I was shooting for has been implemented and passes all of it's unit tests. The outstanding pull requests aren't against the FreeRTOS wrapper code, but either against port.c, which is a derivation of someone else's POSIX simulator (not actually wrapper code at all), or a request to support MAC PCs in simulation, which I don't have and thus can't commit to supporting. (And there's one good one about cleanup, which requires someone to write all of that cleanup code in the FreeRTOS core itself, so it can be properly implemented in port.c.) When I get some more free time, I'd like to add a few more things (see the TODO list). If there's something you specifically need that's missing, let me know.  Best regards.
