### ISSUE TITLE
FreeRTOS EventBits

### ISSUE THREAD

**Issue by danilopucci** [michaelbecker/freertos-addons#4]
Hi Michael,

It is a great job what you have done! I have used your FreeRTOS Wrapper to test and with some foo project (hobby) and I have one question, do you intend to make a wrapper for EventBits?

**Comment by michaelbecker** [comment]
Yes actually, now that there's a request for it I'll add it to my list.

**Comment by danilopucci** [comment]
Hi Michael,

I forked and made the wrapper to EventGroups. It would be great if you can check it. 
I tested it on my project and everything is working fine (actually it was easy because it just functions wrappers without any logic). I tried to follow your code style.

If everything is fine for you, I will try to make the demo examples to run it on Linux and maybe ask you a pull request.

Thanks

**Comment by tothero** [comment]
Also interested in this. Could you please make a PR from your changes?

**Comment by michaelbecker** [comment]
I've merged Danilo's Event Groups classes into the master branch. Closing this issue.
