### ISSUE TITLE
Thoughts on upstream Linux port?

### ISSUE THREAD

**Issue by anthonyclark-as** [michaelbecker/freertos-addons#49]
Michael,

Thanks for the continued support of your POSIX/Linux port of FreeRTOS. I was browsing the new source for FreeRTOS v10.4.4 and realized a NEW "official" Third-Party Posix port is being tracked. Here is documentation that seems updated: https://www.freertos.org/FreeRTOS-simulator-for-Linux.html

And here is the source: https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/main/portable/ThirdParty/GCC/Posix.

I'm wondering what your thoughts are on this port. There seems to be a lot of similarities both in `port.c` and `portmacro.h`. 

Thanks!

**Comment by michaelbecker** [comment]
If there is a supported Linux / Posix port, then I'm all in favor of using it. To that end I've been working on moving all of the Demos I provided from the copy / tweaked version I had been including to use the "official" ThirdParty port instead. Thanks for making me aware of this.
