### ISSUE TITLE
freeRTOS handles protected

### ISSUE THREAD

**Issue by basti0001** [michaelbecker/freertos-addons#5]
Hi Michael,
1rst of all: nice work on this c++ wrapper stuff. Really good job. Thx for sharing this to the world!! Hopefully I can help to improve. ;-)

All of the freeRTOS handles (semaphore, mutex etc.) are declared as protected for "non application" use according to your doc. Is there a special reason for this? 

Background: freeRTOS supplies vTraceSetQueueName(), vTraceSetMutexName() and vTraceSetSemaphoreName() methods to set the trace items names. Really helpful for using TraceAnalyzer from percipio. 

So making this items public would get access to this properties.
Of course also a possible solution would be to implement a public "get()" method for the private pointers e.g.

SemaphoreHandle_t *get_Semaphore() {return &handle}

The application could then use 

vTraceSetSemaphoreName(MySem->get_handle(), "MyName");

How do you think about this one? Would improve this nice wrapper classes from my kind of view.

Cheers

Sebastian

**Comment by basti0001** [comment]
Hi again,
2nd thought of this matter: Since in regular usage this property is only set once (can't imagine why to change a vTraceName during runtime, we could overload the constructors of queues, semaphores and mutexes e.g.:
Queue(UBaseType_t maxItems, UBaseType_t itemSize);
-->
Queue(const std::string AName, UBaseType_t maxItems, UBaseType_t itemSize);

The overloaded constructor calls the default constructor. in addition we set
vTraceSetQueueName(this->handle, &AName[0u]);

No changes in properties, no get/set methods needed.

Sebastian

**Comment by michaelbecker** [comment]
Hi Sebastian,

I've been looking into this, and the APIs that you are referencing (vTraceSetQueueName, vTraceSetMutexName, vTraceSetSemaphoreName) are not FreeRTOS APIs. If I grep the entire FreeRTOS source tree they never appear. I suspect these are APIs from the Tracealyzer tool from https://percepio.com. Now, I think that the idea of building in trace capabilities is a great one, but for this project the focus is on FreeRTOS only, so I won't be integrating 3rd party calls into the wrappers.

Regarding creating getters for the handles in general, I'm on the fence here. I see potential value in allowing access to the handles for tracing. On the other hand, providing this access violates the principle of data encapsulation, at which point it may be easier to just make the handles public, which I don't want to do. I think the best long term solution would be in a future release to integrate whatever trace capabilities FreeRTOS makes public and integrate these into the wrappers themselves.

Best regards,
-Mike

**Comment by basti0001** [comment]
Hi Mike,
yes you are right. This API calls are from the percpio lib for tracing freeRTOS. I did not have this in mind when opening this request. You are right, integrating 3rd party components or even API calls is a big overhead..and as you mentioned not you aim.

I had a look on the freeRTOS page. They have several links for tracing and they recommend using trace analyzer. However there are no freeRTOS based public tracing API's. Maybe in the future. Meanwhile I'm happy with the work around; using as mentioned above the overloaded constructor calling the base constructor and setting the vTraceXYZ stuff. Making the handles public also would seem a little odd and vs. the basic idea of object orientated programming for the wrapper classes. 

Thx for your time, guess we close this issue. Let's see if there will be freeRTOS trace API stuff in the future. 

Best regards

Sebastian
