### ISSUE TITLE
Plain malloc - why there is no RTOS thread safe memory allocation?

### ISSUE THREAD

**Issue by kaamil1984** [michaelbecker/freertos-addons#51]
Hi,

Thats actually might be not an issue. I want to ask why there is `malloc` instead of `pvPortMalloc`? 
I found it here:

https://github.com/michaelbecker/freertos-addons/blob/e497a1625a30e42935149a4b4b52c60545aaf598/c/Source/read_write_lock.c#L202

regards
Kamil

**Comment by michaelbecker** [comment]
There is actually a lot to this question, and an answer isn't as straightforward as one might think. 

First, there strange sometimes recursive relationship between pvPortMalloc and plain old malloc. Every embedded compiler I've worked on has supported malloc. And some of them support adding hooks to grab and release a mutex to protect the operation. But FreeRTOS has implemented their own malloc, pvPortMalloc, which in one heap manager actually calls malloc. So to me it's not obvious which to prefer. 

Second, the pvPortMalloc protects itself by disabling the entire scheduler, which seems kind of extreme to me. I'd prefer to just grab a mutex, so threads not allocating memory are not impacted.

Third, in an embedded system, I have never been OK with allocating memory at run-time. I am OK with allocating memory at the system startup, basically an allocate once and never free pattern. If you need some sort of pool of memory at run-time, you should be using fixed sized pools to do so.

So, the answer is "it depends." If your Use Case seems to prefer calling pvPortMalloc, then by all means feel free to replace the malloc calls. :-)
